[project]
name = "voting-app"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Giang Ngo", email = "giangblackk@gmail.com"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
